WAZO-2513 wazo-plugind-cli consume on headers
wazo-platform/wazo-plugind-cli pull request #11
Opened 2022-05-27 14:39 UTC by ja0x

2022-05-27 20:39 UTC, pc-m requested changes
It looks fine but I get the following error when installing a plugin that can be installed on `master`
```
root@pcm-dev-0:~/wazo-res-stasis-amqp# wazo-plugind-cli -c "install git https://github.com/sboily/wazo-calld-queue"
extracting...
validating...
completed
root@pcm-dev-0:~/wazo-res-stasis-amqp# wazo-plugind-cli -c "uninstall sboily/wazo-calld-queue"
starting...
removing...
Traceback (most recent call last):
  File "/usr/local/bin/wazo-plugind-cli", line 11, in <module>
    load_entry_point('wazo-plugind-cli', 'console_scripts', 'wazo-plugind-cli')()
  File "/usr/src/wazo/wazo-plugind-cli/wazo_plugind_cli/main.py", line 42, in main
    interpreter.execute_command_line(command_name)
  File "/usr/lib/python3/dist-packages/xivo/cli/facade.py", line 65, in execute_command_line
    executor.execute()
  File "/usr/lib/python3/dist-packages/xivo/cli/executor.py", line 26, in execute
    self._process_next_command(raw_command_line)
  File "/usr/lib/python3/dist-packages/xivo/cli/executor.py", line 44, in _process_next_command
    self._error_handler.on_exception(e)
  File "/usr/lib/python3/dist-packages/xivo/cli/executor.py", line 40, in _process_next_command
    command.execute(*execute_args)
  File "/usr/src/wazo/wazo-plugind-cli/wazo_plugind_cli/command.py", line 31, in execute
    self.execute_sync(*args[:-1])
  File "/usr/src/wazo/wazo-plugind-cli/wazo_plugind_cli/command.py", line 37, in execute_sync
    last_status = self._wait_for_progress(consumer, command_uuid)
  File "/usr/src/wazo/wazo-plugind-cli/wazo_plugind_cli/command.py", line 44, in _wait_for_progress
    if message['data']['uuid'] != command_uuid:
KeyError: 'uuid'
```
I did not investigate this problem further, sometimes I have this error during the install sometimes I don't receive the error :man_shrugging:

2022-05-30 12:46 UTC, ja0x commented
On it, the exception was caused by switching from routing key to headers.  Since we don't bind on any specific headers, we receive all messages, some of which might not have the field `uuid`.  

Fixing by adding a quick check that message is valid for our use-case

2022-05-30 12:56 UTC, pc-m commented
> On it, the exception was caused by switching from routing key to headers. Since we don't bind on any specific headers, we receive all messages, some of which might not have the field `uuid`.
> 
> Fixing by adding a quick check that message is valid for our use-case

It works!

2022-05-30 12:56 UTC, pc-m approved these changes

2022-05-30 12:59 UTC, merged